version: "3.9"

services:
  eve-image-manager:
    build: .
    container_name: eve-image-manager
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
